Server started in port8000
Context path with cryptographic materials exists
Error post FabcarController_init SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at FabricControllerAdapter.<anonymous> (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-common-fabric-helper/src/client.helper.ts:198:25)
    at step (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:107:62)
    at <anonymous>
Error post FabcarController_init SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at FabricControllerAdapter.<anonymous> (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-common-fabric-helper/src/client.helper.ts:198:25)
    at step (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:107:62)
    at <anonymous>
Error post FabcarController_init SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at FabricControllerAdapter.<anonymous> (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-common-fabric-helper/src/client.helper.ts:198:25)
    at step (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:107:62)
    at <anonymous>
Error post FabcarController_init SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at FabricControllerAdapter.<anonymous> (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-common-fabric-helper/src/client.helper.ts:198:25)
    at step (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:107:62)
    at <anonymous>
Server started in port8000
Context path with cryptographic materials exists
Error post FabcarController_init SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at FabricControllerAdapter.<anonymous> (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-common-fabric-helper/src/client.helper.ts:198:25)
    at step (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:107:62)
    at <anonymous>
Server started in port8000
Context path with cryptographic materials exists
Server started in port8000
Context path with cryptographic materials exists
Server started in port8000
Context path with cryptographic materials exists
Server started in port8000
Context path with cryptographic materials exists
Server started in port8000
Context path with cryptographic materials exists
Server started in port8000
Context path with cryptographic materials exists
Server started in port8000
Context path with cryptographic materials exists
Error get FabcarController_getAll Error: 
    CLIENT_RES_ERR
    There was a problem while invoking the chaincode
    Chaincode error, this is a wrapper around the responses

    Original stack:
    {"name":"Error","status":400,"message":"no function of name: fabcar_getAll found","stack":"Error: no function of name: fabcar_getAll found"}
    
    at ClientResponseError.BaseError [as constructor] (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-core-errors/src/base.error.ts:18:5)
    at new ClientResponseError (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-core-errors/src/client.errors.ts:16:5)
    at FabricControllerAdapter.<anonymous> (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/src/fabric.controller-adapter.ts:41:13)
    at step (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:136:27)
    at Object.throw (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:117:57)
    at rejected (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:108:69)
    at <anonymous>
Server started in port8000
Context path with cryptographic materials exists
Error get FabcarController_getAll Error: 
    CLIENT_RES_ERR
    There was a problem while invoking the chaincode
    Chaincode error, this is a wrapper around the responses

    Original stack:
    {"name":"Error","status":400,"message":"no function of name: fabcar_getAll found","stack":"Error: no function of name: fabcar_getAll found"}
    
    at ClientResponseError.BaseError [as constructor] (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-core-errors/src/base.error.ts:18:5)
    at new ClientResponseError (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-core-errors/src/client.errors.ts:16:5)
    at FabricControllerAdapter.<anonymous> (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/src/fabric.controller-adapter.ts:41:13)
    at step (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:136:27)
    at Object.throw (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:117:57)
    at rejected (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:108:69)
    at <anonymous>
2019-06-23T17:53:24.468Z - [33mwarn[39m: [ChannelEventHub.js]: Error notifacation callback failed message=this._onErrorFn is not a function, stack=TypeError: this._onErrorFn is not a function
    at EventRegistration.onError (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/lib/ChannelEventHub.js:1570:9)
    at ChannelEventHub._closeAllCallbacks (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/lib/ChannelEventHub.js:773:15)
    at ChannelEventHub._disconnect (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/lib/ChannelEventHub.js:541:8)
    at ClientDuplexStream._stream.on (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/lib/ChannelEventHub.js:491:10)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at ClientDuplexStream._emitStatusIfDone (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/node_modules/grpc/src/client.js:236:12)
    at ClientDuplexStream._receiveStatus (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/node_modules/grpc/src/client.js:213:8)
    at Object.onReceiveStatus (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1290:15)
    at InterceptingListener._callNext (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:564:42)
Error get FabcarController_getAll Error: 
    CLIENT_RES_ERR
    There was a problem while invoking the chaincode
    Chaincode error, this is a wrapper around the responses

    Original stack:
    Error: Failed to connect before the deadline URL:grpc://localhost:7051
    at checkState (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/node_modules/grpc/src/client.js:720:16)
    
    at ClientResponseError.BaseError [as constructor] (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-core-errors/src/base.error.ts:18:5)
    at new ClientResponseError (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-core-errors/src/client.errors.ts:16:5)
    at FabricControllerAdapter.<anonymous> (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/src/fabric.controller-adapter.ts:35:15)
    at step (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:136:27)
    at Object.throw (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:117:57)
    at rejected (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:108:69)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Server started in port8000
Context path with cryptographic materials exists
Server started in port8000
Context path with cryptographic materials exists
Server started in port8000
Context path with cryptographic materials exists
Server started in port8000
Context path with cryptographic materials exists
Error post FabcarController_create Error: Undefined parameters received as part of the transaction, check how the function is being called
    at /Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-common-fabric-helper/src/client.helper.ts:320:15
    at Array.map (<anonymous>)
    at FabricControllerAdapter.<anonymous> (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-common-fabric-helper/src/client.helper.ts:317:41)
    at step (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:117:57)
    at /Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:106:16)
    at FabricControllerAdapter.ClientHelper.sendTransactionProposal (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-common-fabric-helper/dist/src/client.helper.js:378:24)
    at FabricControllerAdapter.<anonymous> (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-common-fabric-helper/src/client.helper.ts:180:45)
Error post FabcarController_create Error: 
    CLIENT_RES_ERR
    There was a problem while invoking the chaincode
    Chaincode error, this is a wrapper around the responses

    Original stack:
    Error: transaction returned with failure: {"name":"Error","status":500,"message":"Model io.worldsibu.fabcar is missing the 'id' property \n{\"type\":\"io.worldsibu.fabcar\",\"make\":\"Hyundai\",\"model\":\"A\",\"colour\":\"Black\",\"owner\":\"Diego\"}"}
    at self._endorserClient.processProposal (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/lib/Peer.js:140:36)
    at Object.onReceiveStatus (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:1191:9)
    at InterceptingListener._callNext (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/Users/diestrin/Documents/Research/fabcar/node_modules/fabric-client/node_modules/grpc/src/client_interceptors.js:841:24)
    
    at ClientResponseError.BaseError [as constructor] (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-core-errors/src/base.error.ts:18:5)
    at new ClientResponseError (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/node_modules/@worldsibu/convector-core-errors/src/client.errors.ts:16:5)
    at FabricControllerAdapter.<anonymous> (/Users/diestrin/Documents/Research/fabcar/node_modules/@worldsibu/convector-adapter-fabric/src/fabric.controller-adapter.ts:35:15)
    at step (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:136:27)
    at Object.throw (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:117:57)
    at rejected (/Users/diestrin/Documents/Research/fabcar/node_modules/tslib/tslib.js:108:69)
    at <anonymous>
